### PR TITLE
Added some documentation tips

### PR DESCRIPTION
**Pull request by CarlSargunar**
This created a self-documenting API test using the VS Code Rest extension

### CODE REVIEW

**Comment by prjseal** [comment]
Thanks Carl, this is great. 

During the call we discovered that my example body requests were incorrect, are you able to update your PR to include to correct body properties. Here is some of the code from the api call code for reference.

``` js
        var data = {
            "InstallUmbracoTemplate": psw.controls.installUmbracoTemplate.checked,
            "UmbracoTemplateVersion": psw.controls.umbracoTemplateVersion.value,
            "Packages": psw.controls.packages.value,
            "UserEmail": psw.controls.userEmail.value,
            "ProjectName": psw.controls.projectName.value,
            "CreateSolutionFile": psw.controls.createSolutionFile.checked,
            "SolutionName": psw.controls.solutionName.value,
            "UseUnattendedInstall": psw.controls.useUnattendedInstall.checked,
            "DatabaseType": psw.controls.databaseType.value,
            "UserPassword": psw.controls.userPassword.value,
            "UmbracoTemplateVersion": psw.controls.umbracoTemplateVersion.value,
            "UserFriendlyName": psw.controls.userFriendlyName.value,
            "IncludeStarterKit": psw.controls.includeStarterKit.checked,
            "StarterKitPackage": psw.controls.starterKitPackage.value
        }
```

**Comment by CarlSargunar** [comment]
Oh, ok - I had 2 calls in the http file, they seemed to give OK responses?

E.g for the following request : 

{
	"InstallUmbracoTemplate": true,
	"UmbracoTemplateVersion": "",
	"Packages": "uSync,uSync.Complete",
	"UserEmail": "admin@example.com",
	"ProjectName": "MyProject",
	"DatanaseType": "fsdfsf",
	"CreateSolutionFile": true,
	"SolutionName": "MySolution",
	"DatabaseType": "SQLite",
	"UseUnattendedInstall": true,
	"UserPassword": null,
	"UmbracoVersions": null,
	"UserFriendlyName": null,
	"IncludeStarterKit": true,
	"StarterKitPackage": null
}


I got back this response :

# Ensure we have the latest Umbraco templates
dotnet new -i Umbraco.Templates

# Create solution/project
dotnet new sln --name "MySolution"
dotnet new umbraco -n "MyProject" --friendly-name "Administrator" --email "admin@example.com" --password "1234567890" --connection-string "Data Source=|DataDirectory|/Umbraco.sqlite.db;Cache=Shared;Foreign Keys=True;Pooling=True"
$env:Umbraco__CMS__Global__InstallMissingDatabase="true"
$env:ConnectionStrings__umbracoDbDSN_ProviderName="Microsoft.Data.SQLite"
dotnet sln add "MyProject"

#Add starter kit
dotnet add "MyProject" package Umbraco.TheStarterKit

#Add Packages
dotnet add "MyProject" package uSync
dotnet add "MyProject" package uSync.Complete

dotnet run --project "MyProject"
#Running

**Comment by CarlSargunar** [comment]
Formatting got a little weird because it's markdown, but the response looked OK. This is a photo of the response

image

**Comment by prjseal** [comment]
Hi Carl
The body was wrong. Perhaps you didn't see that part, database type was in there twice (one was spelled incorrectly) and UmbracoVersions should be UmbracoTemplateVersion
I can edit it if you want

**Comment by CarlSargunar** [comment]
Ah - I know what happened - I pushed my PR before your stream was over, so the changes you did weren't in my PR, but I also added a test action in the API. I've merged those changes in now so it should all be good

cheers mate

**Comment by prjseal** [comment]
merged thanks Carl

**Comment by CarlSargunar** [comment]
OMG - Sorry paul, I misunderstood - thanks for correcting it in the request. Weird that it still worked, but I guess if those parameters didn't match up the API still responded OK.

Cheers

**Pull request merged**
