### PR TITLE
#change: Added MarketplacePackageService

### PR DESCRIPTION
**Pull request by hannakfoo**
Hi Paul,

I have create this PR to connect to the Umbraco Marketplace API, but I discovered 1issue with the API: when you call the API with PageIndex 5 and PageSize 50 it still returns 50 results which lead to double package in the result.  
I tried checking before adding the range if a package should be added to the result List (allPackages) but failed.

Besides this issue also the category to which a package belongs isnt available in the response. I could do another API call by packageId to get this information but dont know what you think? See the swagger docs: https://api.marketplace.umbraco.com/index.html it is an extra API call which might lead to less performance?

### CODE REVIEW

**Comment by prjseal** [comment]
Hi. This is great progress. When we do the first api call to get 50 we also get the total results. Can we just make the last call be the size of the remaining amount. So if there are 286 the we would do 5 pages of 50 and 1 page of 36. Are you ok to modify it to do that?

**Comment by prjseal** [comment]
Also don’t worry about the category. We don’t need that at this stage

**Comment by hannakfoo** [comment]
Hi Paul, the latest commits seems to fix the category name by adding it to the API call field query params and also the tail of remaining amount. Only seems to give some double results, but maybe you can check?

**Comment by prjseal** [comment]
Thanks for getting it this far. I'll take a look at the duplicates and category issues later.

**Comment by prjseal** [comment]
Hi, I worked out what was wrong. Just trying to merge and push my changes to fix it now. Thanks so much for the PR

**Comment by prjseal** [comment]
It's working now and I have pushed it live. Thanks again

**Pull request merged**
